# This name needs to be the same as the node name specified in the launch file for Bobot utils. DO NOT CHANGE IT... unless you change the node names
# Servo Jerk node parameters (Device, IO pins that are being used, etc)
ServoJerk:
  ros__parameters:
    arduino:
      # Create an array of pins
      pins: ["pin1", "pin2", "pin3", "pin4"]
      # -
      #   pin_num: 1
      #   type: "digital"
      #   read_type: "input"
      # -
      #   pin_num: 2
      #   type: "PWM"
      #   read_type: "output"

AltitudeMonitor:
  ros__parameters:
    arduino:
      # Create an array of pins
      pins: ["pin1", "pin2", "pin3", "pin4"]
      # -
      #   pin_num: 1
      #   type: "digital"
      #   read_type: "input"
      # -
      #   pin_num: 2
      #   type: "PWM"
      #   read_type: "output"













  

  

