/**:
  ros__parameters:

    # GENERAL SERVO PARAMETERS
    NUM_JOINTS: 10 # Integer value
    BOBOT_NAME: "bb_bobot_1"
    LOGGING_SAMPLE_RATE: 10 # value is in Hz

    # SERVO JERKER NODE PARAMETERS
    JERK_RATE: 1 # Jerk rate is in Hz
    SERVOS_TO_JERK_ID: ["ID-1", "ID-2", "ID-3"]
    SERVOS_TO_JERK: [1,2,3]
    MAX_ANGLE: 150
    MIN_ANGLE: 130
    SERVO_IS_SIMULATED: false

    # ALTITUDE NODE PARAMETERS
    SAMPLE_RATE: 100 # value is in Hz
    MAX_ALTITUDE: 82000 # feet - Change per flight!
    ALT_IS_SIMULATED: true


